@baseUrl = http://localhost:5262

### Get all products
GET {{baseUrl}}/shop/products
Accept: application/json

### Create an order
POST {{baseUrl}}/shop/order
Content-Type: application/json

{
    "productId": 1,
    "quantity": 2,
    "userEmail": "test@example.com"
}